import { Inter } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/components/navbarpage";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Zotok",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-white md:bg-[#ECF0F6]">
      <body className="m-2 font-hoves">
        <NavbarPage  />
        {children}</body>
    </html>
  );
}
